"""Seed des questions de quiz pour chaque cours"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
os.chdir(os.path.dirname(__file__))

from app.core.database import SessionLocal, engine, Base
from app.models import *
from app.models.quiz import QuizQuestion
Base.metadata.create_all(bind=engine)

db = SessionLocal()

QUIZ_DATA = {
    1: [  # Comprendre son sol
        {"question": "Qu'est-ce que le pH du sol mesure ?",
         "option_a": "La quantité d'eau dans le sol",
         "option_b": "L'acidité ou l'alcalinité du sol",
         "option_c": "La profondeur des racines",
         "option_d": "La quantité d'engrais nécessaire",
         "bonne_reponse": "b",
         "explication": "Le pH mesure si votre sol est acide (pH < 7), neutre (pH = 7) ou basique/alcalin (pH > 7). C'est le paramètre le plus important à connaître pour choisir ses cultures."},
        {"question": "Vous faites le test du boudin avec de la terre humide. Le boudin ne tient pas et s'effrite. Quel type de sol avez-vous ?",
         "option_a": "Sol argileux",
         "option_b": "Sol limoneux",
         "option_c": "Sol sableux",
         "option_d": "Sol argilo-limoneux",
         "bonne_reponse": "c",
         "explication": "Un sol sableux ne forme pas de boudin car il manque d'argile pour coller. Il s'effrite immédiatement entre les doigts."},
        {"question": "Un agriculteur mesure un pH de 4,8 dans son champ. Quelle action doit-il faire EN PRIORITÉ ?",
         "option_a": "Ajouter de l'urée (engrais azoté)",
         "option_b": "Effectuer un chaulage (apport de chaux)",
         "option_c": "Arroser davantage",
         "option_d": "Rien, c'est parfait pour le cacao",
         "bonne_reponse": "b",
         "explication": "Un pH de 4,8 est très acide. Il faut impérativement apporter de la chaux agricole pour corriger l'acidité avant de planter quoi que ce soit."},
        {"question": "Quelle est la meilleure façon d'améliorer un sol pauvre naturellement ?",
         "option_a": "Mettre beaucoup d'engrais chimique",
         "option_b": "Apporter du compost ou du fumier bien décomposé",
         "option_c": "Arroser abondamment",
         "option_d": "Retourner le sol profondément",
         "bonne_reponse": "b",
         "explication": "Le compost et le fumier décomposé enrichissent le sol en matière organique, améliorent sa structure, retiennent l'eau et nourrissent les micro-organismes bénéfiques."},
        {"question": "Quelle plante est la PLUS tolérante à presque tous les types de sols au Cameroun ?",
         "option_a": "Tomate",
         "option_b": "Café Robusta",
         "option_c": "Manioc",
         "option_d": "Ananas",
         "bonne_reponse": "c",
         "explication": "Le manioc est la culture la plus tolérante. Il pousse sur des sols sableux, argileux, acides ou pauvres. C'est pourquoi c'est la culture vivrière de base du Cameroun."},
    ],
    2: [  # Cacao
        {"question": "Quelle est la densité de plantation recommandée pour le cacao ?",
         "option_a": "1m x 1m (10 000 plants/ha)",
         "option_b": "3m x 3m (1111 plants/ha)",
         "option_c": "5m x 5m (400 plants/ha)",
         "option_d": "10m x 10m (100 plants/ha)",
         "bonne_reponse": "b",
         "explication": "L'écartement standard pour le cacao est 3m x 3m, soit environ 1111 plants par hectare. Cela donne suffisamment d'espace à chaque arbre pour se développer et être entretenu."},
        {"question": "Pourquoi le cacao a-t-il besoin d'ombrage les premières années ?",
         "option_a": "Pour économiser l'eau d'arrosage",
         "option_b": "Car le jeune cacaoyer est sensible au soleil direct",
         "option_c": "Pour empêcher les mauvaises herbes",
         "option_d": "Pour attirer les pollinisateurs",
         "bonne_reponse": "b",
         "explication": "Le jeune cacaoyer est une plante de sous-bois. Il a besoin d'environ 50% d'ombre les 3 premières années. Les bananiers sont souvent utilisés comme plantes d'ombrage temporaires."},
        {"question": "Combien de jours faut-il pour fermenter les fèves de cacao correctement ?",
         "option_a": "1-2 jours",
         "option_b": "5-7 jours",
         "option_c": "15-20 jours",
         "option_d": "La fermentation n'est pas nécessaire",
         "bonne_reponse": "b",
         "explication": "La fermentation dure 5 à 7 jours. C'est une étape CRUCIALE qui développe les arômes du chocolat. Une fève mal fermentée perd 30 à 40% de sa valeur marchande."},
        {"question": "Quel est le principal avantage des plants certifiés IRAD par rapport aux plants sauvages ?",
         "option_a": "Ils coûtent moins cher",
         "option_b": "Ils poussent plus vite et résistent mieux aux maladies",
         "option_c": "Ils n'ont pas besoin d'entretien",
         "option_d": "Ils produisent dès la première année",
         "bonne_reponse": "b",
         "explication": "Les plants certifiés IRAD sont des variétés hybrides sélectionnées. Ils produisent 3x plus que les plants sauvages et résistent mieux à la pourriture brune."},
        {"question": "Que signifie une cabosse qui sonne creux quand on la frappe ?",
         "option_a": "Elle est malade",
         "option_b": "Elle est mûre et prête à récolter",
         "option_c": "Elle est vide à l'intérieur",
         "option_d": "Elle manque d'eau",
         "bonne_reponse": "b",
         "explication": "Une cabosse mûre sonne creux car la pulpe (mucilage) autour des fèves s'est développée et ne colle plus à la coque. C'est le signe que les fèves sont prêtes."},
    ],
    3: [  # Maraîchage
        {"question": "Quelle est la largeur recommandée pour une planche maraîchère ?",
         "option_a": "50 cm",
         "option_b": "1 mètre",
         "option_c": "2 mètres",
         "option_d": "3 mètres",
         "bonne_reponse": "b",
         "explication": "1 mètre de large permet de travailler facilement des deux côtés sans marcher sur la planche. Si la planche est trop large, on piétine le sol et on compacte les racines."},
        {"question": "Pourquoi arrose-t-on les légumes le MATIN plutôt que le soir ?",
         "option_a": "L'eau est plus froide le matin",
         "option_b": "Le soleil aide les plantes à mieux absorber l'eau",
         "option_c": "Pour éviter que les feuilles mouillées développent des maladies la nuit",
         "option_d": "Il n'y a pas de différence",
         "bonne_reponse": "c",
         "explication": "Les feuilles mouillées la nuit favorisent le développement des champignons (mildiou, etc.) car il fait frais et humide. Le matin, le soleil sèche rapidement les feuilles."},
        {"question": "Quelle est la durée de cycle de la tomate ?",
         "option_a": "30 jours",
         "option_b": "60 jours",
         "option_c": "90 jours",
         "option_d": "180 jours",
         "bonne_reponse": "c",
         "explication": "La tomate a un cycle de 90 jours (3 mois) : environ 3-4 semaines en pépinière + 2 mois de croissance et production au champ."},
        {"question": "Comment réaliser un système d'irrigation économique avec des bouteilles ?",
         "option_a": "Percer le bouchon et laisser l'eau couler",
         "option_b": "Percer de petits trous dans la bouteille, l'enterrer à mi-hauteur près des plants",
         "option_c": "Poser les bouteilles pleines à côté des plants",
         "option_d": "Remplir les sillons avec des bouteilles percées",
         "bonne_reponse": "b",
         "explication": "En perçant de petits trous dans une bouteille de 5L et en l'enterrant à mi-hauteur, l'eau s'infiltre lentement pendant 2-3 jours directement aux racines. Économique et efficace !"},
    ],
    4: [  # Ravageurs et maladies
        {"question": "Vous voyez des feuilles avec des taches brunes entourées d'un halo JAUNE. De quoi s'agit-il ?",
         "option_a": "Manque d'eau",
         "option_b": "Maladie fongique (champignon)",
         "option_c": "Maladie bactérienne",
         "option_d": "Excès d'engrais",
         "bonne_reponse": "b",
         "explication": "Les taches brunes entourées d'un halo jaune sont caractéristiques des maladies fongiques. Le halo jaune correspond à la zone où les toxines du champignon se propagent."},
        {"question": "Comment distinguer un puceron d'une autre maladie ?",
         "option_a": "Les pucerons font des taches noires sur les feuilles",
         "option_b": "On voit de petits insectes verts ou noirs groupés sous les feuilles",
         "option_c": "Les feuilles deviennent rouges",
         "option_d": "Les tiges se cassent facilement",
         "bonne_reponse": "b",
         "explication": "Les pucerons sont de petits insectes (2-3mm) qui vivent en colonies sous les feuilles. Ils sucent la sève et transmettent des virus. On les reconnaît à leur aspect brillant et leur présence en groupe."},
        {"question": "Quel est le traitement LOCAL efficace contre les pucerons ?",
         "option_a": "Arroser abondamment",
         "option_b": "Pulvériser du savon noir dilué sous les feuilles",
         "option_c": "Mettre de la chaux sur le sol",
         "option_d": "Retirer toutes les feuilles",
         "bonne_reponse": "b",
         "explication": "Le savon noir (savon de ménage) dilué dans l'eau tue les pucerons par contact en bouchant leurs pores respiratoires. C'est économique, efficace et sans danger pour les plants."},
        {"question": "Quelle est la MEILLEURE stratégie pour éviter les maladies dans un champ ?",
         "option_a": "Pulvériser des pesticides toutes les semaines",
         "option_b": "Planter très serré pour étouffer les mauvaises herbes",
         "option_c": "Rotation des cultures, espacement correct, nettoyage du champ",
         "option_d": "Arroser beaucoup pour diluer les maladies",
         "bonne_reponse": "c",
         "explication": "La lutte intégrée (rotation, espacement, nettoyage) prévient 70% des maladies. Les pesticides doivent être le DERNIER recours, pas le premier. Prévenir coûte 10x moins cher que guérir."},
    ],
    5: [  # Manioc
        {"question": "Quelle longueur doit avoir une bonne bouture de manioc ?",
         "option_a": "5-10 cm",
         "option_b": "25-30 cm",
         "option_c": "50-60 cm",
         "option_d": "La longueur n'a pas d'importance",
         "bonne_reponse": "b",
         "explication": "Une bouture de 25-30 cm avec 3 à 5 nœuds (bourgeons) est idéale. Trop courte, elle manque de réserves. Trop longue, elle est difficile à planter et gaspille la tige."},
        {"question": "Pourquoi ne faut-il pas planter du manioc en bas-fonds (zones inondables) ?",
         "option_a": "Le manioc n'aime pas l'eau de pluie",
         "option_b": "Les tubercules pourrissent si le sol est trop humide",
         "option_c": "Le manioc préfère les hautes altitudes",
         "option_d": "Les insectes y sont plus nombreux",
         "bonne_reponse": "b",
         "explication": "Les tubercules de manioc se forment sous terre. Un sol constamment saturé d'eau prive les racines d'oxygène et favorise les pourritures. Il faut planter en terrain drainant ou sur des billons."},
        {"question": "Combien de temps maximum peut-on conserver des tubercules de manioc FRAIS après récolte ?",
         "option_a": "1 semaine",
         "option_b": "3-5 jours",
         "option_c": "1 mois",
         "option_d": "3 mois",
         "bonne_reponse": "b",
         "explication": "Le manioc frais se détériore très vite (3 à 5 jours). C'est pourquoi il faut le transformer rapidement en gari, cossettes ou farine pour une conservation longue durée."},
        {"question": "Quelle variété de manioc est recommandée par l'IRAD pour sa résistance aux maladies ?",
         "option_a": "Variété locale non identifiée",
         "option_b": "TME 419",
         "option_c": "Toute variété pousse de la même façon",
         "option_d": "Il n'existe pas de variétés améliorées au Cameroun",
         "bonne_reponse": "b",
         "explication": "La variété TME 419 est recommandée par l'IRAD car elle résiste à la mosaïque et à la bactériose, et produit 30 à 50 tonnes par hectare — bien plus que les variétés locales ordinaires."},
    ],
}

# Supprimer anciens quiz
db.query(QuizQuestion).delete()
db.commit()

total = 0
for cours_id, questions in QUIZ_DATA.items():
    for i, q in enumerate(questions):
        question = QuizQuestion(cours_id=cours_id, ordre=i+1, **q)
        db.add(question)
        total += 1

db.commit()
db.close()
print(f"OK: {total} questions de quiz inserees dans {len(QUIZ_DATA)} cours")
